---
name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    if: ref != 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: lts/hydrogen
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Run tests
        run: npm test

      - name: Semantic release dry-run
        run: npm run semantic-release -- --dry-run
